### PR TITLE
Feature/132/party donations route

### PR DESCRIPTION
**Pull request by romeonicholas**
First deliverable was rescoped to _only_ the homepage party donation route.  In this branch: party donation tables have been created, the tables have been populated, the response to the homepage route has been formatted for the front end to utilize, and basic tests have been added.

### CODE REVIEW

**Comment by RichardKruemmel** [comment]
Inside `src.cron_jobs.utils.celan_donations.py` you are importing `src.cron_jobs.data.parties as parties`
As we gitignore the whole data folder it triggers an error as soon the parties file is missing, which won't be on the server nor do I have this file locally available. Maybe just implementing a query to the db might be a better option. What do you think? :)

**Comment by romeonicholas** [comment]
Yeah, this was just a side effect of running all our populate functions locally on this first batch of donations and though I left comments in the function about it I forgot to actually remove the import. The entire scrape -> clean -> populate pipeline will need to be fixed, so I just removed the offending import for now. We can add stories to the backlog for the other problems with populating.

**Comment by romeonicholas** [comment]
Though I don't know what's wrong with the vote tests, were those already failing? Would something have gotten jumbled with all the manual database editing?

**Comment by RichardKruemmel** [comment]
Do we want to have a look together at those tests? It's clear to me why they are failing and I would like to get your input on them as well as I would like to reevaluate our strategy regarding those two tests failing.

**Comment by RichardKruemmel** [comment]
Screenshot 2022-09-30 at 12 03 50

Any idea on how to solve this? It seems important.

**Comment by romeonicholas** [comment]
Yeah, let's talk early next week about the tests. For the logger issue: I don't think there is a code fix, I think it's telling us to do a security review. I don't know what we're logging, where we're saving it, and who has access to the logs, but those are all things we'd need to confirm wouldn't cause problems down the line.

**Comment by RichardKruemmel** [comment]
To-do after Design Feedback:
- [ ] instead of returning monthly donation data points, we need quarterly donation datapoints
- [ ] the route should return the highest quarterly donation, so we don't have to loop through all data points in the front end to determine the highest point on the y-axis

_**still to decide: timeframe of donations**_

**Review by RichardKruemmel — APPROVED** [review]

**Pull request merged**
